backend:
  name: git-gateway
  branch: main
media_folder: "uploads"
public_folder: "/uploads"
collections:
  - name: home
    label: Home
    files:
      - file: "content/home.json"
        label: "Homepage Content"
        name: homepage
        fields:
          - { label: "Hero Title", name: hero_title, widget: string }
          - { label: "Hero Subtext", name: hero_sub, widget: text }
          - { label: "Phone", name: phone, widget: string }
          - { label: "Email", name: email, widget: string }
          - label: KPIs
            name: kpis
            widget: list
            field: { label: Item, name: item, widget: string }
