backend:
  name: git-gateway
  branch: main
  identity: true
  role: admin
media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: home
    label: Home
    files:
      - file: "content/home.json"
        label: "Homepage Content"
        name: homepage
        fields:
          - { label: "Hero Title", name: hero_title, widget: string }
          - { label: "Hero Subtext", name: hero_sub, widget: text }
          - { label: "Phone", name: phone, widget: string }
          - { label: "Email", name: email, widget: string }
          - label: KPIs
            name: kpis
            widget: list
            field: { label: Item, name: item, widget: string }

  - name: services
    label: Services
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Blurb, name: blurb, widget: text }
      - { label: Image, name: image, widget: image }
